language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
 # - npm install -g gulp
  - chmod -R 777 ./node_modules

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wangyong1668"
  - git config user.email "1178166735@qq.com"
  - git add .
  - git commit -m "docs:update articles"
  - git push --force --quiet "https://${wangyong}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/wangyong1668/wangyong1668.github.io.git
